apiVersion: v1
kind: ResourceQuota
metadata:
  name: expenseflow-resource-quota
  namespace: default

spec:
  hard:
    requests.cpu: "1500m"
    requests.memory: "2Gi"

    limits.cpu: "3"
    limits.memory: "3Gi"

    pods: "10"