apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Values.limits.name }}
  namespace: default
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: {{ .Values.limits.defaultRequest.cpu }}
        memory: {{ .Values.limits.defaultRequest.memory }}
      default:
        cpu: {{ .Values.limits.default.cpu }}
        memory: {{ .Values.limits.default.memory }}
      min:
        cpu: {{ .Values.limits.min.cpu }}
        memory: {{ .Values.limits.min.memory }}
      max:
        cpu: {{ .Values.limits.max.cpu }}
        memory: {{ .Values.limits.max.memory }}