apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysqlService.name }} 
spec:
  selector:
    app: {{ .Values.mysql.label }}
  ports:
    - protocol: TCP
      port: {{ .Values.mysql.port }}
      targetPort: {{ .Values.mysql.port }}