apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redisService.name }} 
spec:
  selector:
    app: {{ .Values.redis.label }}
  ports:
    - protocol: TCP
      port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}