apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
stringData:
  DB_USER: {{ .Values.secret.dbUser | quote }}
  DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.mysqlRootPassword | quote }}
  JWT_SECRET: {{ .Values.secret.jwtSecret | quote }}